### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wen-hsiu-hsu** [kevinshu1995/f2e-bus#1]
# TODO 

- [ ] infos
    - [ ] title & vercel domain & api attribute
- [ ] 地圖
    - [ ] GPS 目前位置 marker
    - [ ] 手機板，顯示全螢幕地圖
- [ ] 公車路線圖
- [ ] 更新資料 (定時 & 手動)
- [ ] 收藏公車功能
- [ ] 最新消息頁
- [ ] 常見問題頁
